import villaSeaview from '@/assets/villa-seaview.jpg';
import villaSunset from '@/assets/villa-sunset.jpg';
import villaHillside from '@/assets/villa-hillside.jpg';
import villaPoolNight from '@/assets/villa-pool-night.jpg';
import villaBeachfront from '@/assets/villa-beachfront.jpg';
import villaInterior from '@/assets/villa-interior.jpg';

export type TimelineItemType = 'booking' | 'task' | 'damage' | 'inquiry' | 'pricing' | 'regulatory' | 'community' | 'guest_flow';

export interface TimelineItem {
  id: string;
  type: TimelineItemType;
  timestamp: string;
  title: string;
  subtitle: string;
  status?: string;
  data: Record<string, unknown>;
}

export const propertyImages: Record<string, string> = {
  'Villa Seaview': villaSeaview,
  'Villa Sunset': villaSunset,
  'Villa Hillside': villaHillside,
  'Villa Pool Night': villaPoolNight,
  'Villa Beachfront': villaBeachfront,
  'Villa Interior': villaInterior,
};

export const galleryImages = [villaSeaview, villaSunset, villaHillside, villaPoolNight, villaBeachfront, villaInterior];

export const mockTimeline: TimelineItem[] = [
  {
    id: 'r001',
    type: 'regulatory',
    timestamp: '2026-03-10T15:00:00',
    title: 'TM30 Reminder',
    subtitle: 'John Miller (USA) — ต้องแจ้งภายใน 24 ชม.',
    status: 'pending',
    data: {
      property: 'Villa Seaview',
      guestName: 'John Miller',
      nationality: 'USA',
      documentType: 'TM30',
      deadline: '2026-03-16',
      autoGenerated: true,
      description: 'ระบบสร้าง TM30 อัตโนมัติแล้ว รอเจ้าของกดยืนยันเพื่อส่งออนไลน์',
    },
  },
  {
    id: 'b001',
    type: 'booking',
    timestamp: '2026-03-10T14:30:00',
    title: 'New Booking Confirmed',
    subtitle: 'John & Sarah Miller · 4 guests · 5 nights',
    status: 'confirmed',
    data: {
      guestName: 'John & Sarah Miller',
      property: 'Villa Seaview',
      checkIn: '2026-03-15',
      checkOut: '2026-03-20',
      guests: 4,
      totalPrice: 47500,
      source: 'Airbnb',
      artSeed: 8342,
    },
  },
  {
    id: 'gf001',
    type: 'guest_flow',
    timestamp: '2026-03-10T14:00:00',
    title: 'Self Check-in Sent',
    subtitle: 'QR กุญแจ + WiFi + คู่มือ ส่งให้ John Miller แล้ว',
    status: 'completed',
    data: {
      property: 'Villa Seaview',
      guestName: 'John Miller',
      channel: 'LINE',
      items: ['QR Door Code', 'WiFi', 'House Manual (EN)', 'Google Maps', 'TDAC Reminder'],
      description: 'ส่งข้อมูลเช็คอินอัตโนมัติ ไม่ต้องโทรหาแขก',
    },
  },
  {
    id: 'i001',
    type: 'inquiry',
    timestamp: '2026-03-10T13:15:00',
    title: 'LINE Inquiry',
    subtitle: 'คุณสมชาย ถามราคาสงกรานต์',
    status: 'pending',
    data: {
      guestName: 'คุณสมชาย',
      property: 'Villa Sunset',
      channel: 'LINE',
      language: 'th',
      message: 'สนใจจองวิลล่าช่วงสงกรานต์ 12-16 เมษายน 6 คน ราคาเท่าไหร่ครับ?',
      aiResponse: 'สวัสดีค่ะคุณสมชาย! Villa Sunset ช่วงสงกรานต์ 12-16 เม.ย. (4 คืน) 6 ท่าน ราคาพิเศษ ฿56,000 รวม early check-in ค่ะ 🎉',
      aiConfidence: 0.95,
    },
  },
  {
    id: 't001',
    type: 'task',
    timestamp: '2026-03-10T11:00:00',
    title: 'Cleaning Task',
    subtitle: 'Villa Hillside · Check-out today · คุณน้อย',
    status: 'in_progress',
    data: {
      property: 'Villa Hillside',
      taskType: 'cleaning',
      assignedTo: 'คุณน้อย',
      scheduledTime: '14:00',
      checklist: ['ห้องนอน', 'ห้องน้ำ', 'ครัว', 'สระว่ายน้ำ', 'ผ้าปูที่นอน'],
      autoCreated: true,
    },
  },
  {
    id: 'c001',
    type: 'community',
    timestamp: '2026-03-10T10:30:00',
    title: 'Community Post',
    subtitle: 'คุณวิชัย แชร์: "ช่างแอร์ดี ราคาถูก ซอยบัวขาว"',
    status: 'completed',
    data: {
      region: 'พัทยา',
      author: 'คุณวิชัย',
      message: 'แนะนำช่างแอร์ ช่างเอก 089-xxx-xxxx ซ่อมเร็ว ราคาถูก ซอยบัวขาว ดีทุกครั้งครับ 👍',
      likes: 12,
      replies: 4,
      category: 'vendor',
    },
  },
  {
    id: 'p001',
    type: 'pricing',
    timestamp: '2026-03-10T09:00:00',
    title: 'AI Price Suggestion',
    subtitle: 'สงกรานต์: ฿12,500/night (+38%)',
    status: 'pending',
    data: {
      property: 'Villa Seaview',
      period: 'Apr 10-17 (สงกรานต์)',
      currentPrice: 9000,
      suggestedPrice: 12500,
      multiplier: 1.38,
      demandScore: 87,
      confidence: 0.92,
      factors: ['สงกรานต์ Demand สูง', 'Occupancy โซนใกล้เคียง 92%', 'ฝนน้อยกว่าค่าเฉลี่ย'],
    },
  },
  {
    id: 'd001',
    type: 'damage',
    timestamp: '2026-03-09T16:45:00',
    title: 'Damage Detected',
    subtitle: 'โคมไฟห้องนอนใหญ่แตก · Est. ฿2,800',
    status: 'reported',
    data: {
      property: 'Villa Sunset',
      bookingId: 'b099',
      guestName: 'Mr. Tanaka',
      description: 'โคมไฟตั้งโต๊ะในห้องนอนใหญ่ล้มแตก โป๊ะแตก ฐานบิ่น ตรวจพบโดย AI หลังเช็คเอาท์',
      severity: 'medium',
      estimatedCost: 2800,
      items: ['โคมไฟตั้งโต๊ะ — ห้องนอนใหญ่'],
      aiDetected: true,
      autoChargeReady: true,
      chargeMethod: 'Stripe',
    },
  },
  {
    id: 'b002',
    type: 'booking',
    timestamp: '2026-03-09T10:20:00',
    title: 'Booking Completed',
    subtitle: 'The Tanaka Family · 3 guests · 7 nights',
    status: 'completed',
    data: {
      guestName: 'The Tanaka Family',
      property: 'Villa Hillside',
      checkIn: '2026-03-02',
      checkOut: '2026-03-09',
      guests: 3,
      totalPrice: 63000,
      source: 'Booking.com',
      artSeed: 55219,
    },
  },
];

export const revenueThisMonth = 247500;

export const dashboardStats = {
  revenue: 247500,
  revenueChange: 18.5,
  occupancy: 78,
  occupancyChange: 12,
  overbooking: 0,
  activeTasks: 3,
  pendingInquiries: 2,
  upcomingCheckIns: 1,
  regulatoryPending: 1,
  aiResponseRate: 95,
};

export const properties = [
  { id: 'p1', name: 'Villa Seaview', location: 'พัทยา', bedrooms: 3, bathrooms: 2, basePrice: 9500, status: 'active' as const, occupancy: 82, nextCheckIn: 'Mar 15', rating: 4.9, reviews: 47, image: villaSeaview },
  { id: 'p2', name: 'Villa Sunset', location: 'พัทยา', bedrooms: 4, bathrooms: 3, basePrice: 12000, status: 'active' as const, occupancy: 71, nextCheckIn: 'Mar 18', rating: 4.8, reviews: 32, image: villaSunset },
  { id: 'p3', name: 'Villa Hillside', location: 'ขอนแก่น', bedrooms: 2, bathrooms: 2, basePrice: 7500, status: 'maintenance' as const, occupancy: 65, nextCheckIn: 'Mar 22', rating: 4.7, reviews: 28, image: villaHillside },
  { id: 'p4', name: 'Villa Beachfront', location: 'ภูเก็ต', bedrooms: 5, bathrooms: 4, basePrice: 18000, status: 'active' as const, occupancy: 88, nextCheckIn: 'Mar 12', rating: 4.95, reviews: 63, image: villaBeachfront },
  { id: 'p5', name: 'Villa Pool Night', location: 'สมุย', bedrooms: 3, bathrooms: 3, basePrice: 14000, status: 'active' as const, occupancy: 75, nextCheckIn: 'Mar 20', rating: 4.85, reviews: 41, image: villaPoolNight },
];

export const calendarEvents = [
  { id: 'e1', property: 'Villa Seaview', guest: 'John & Sarah Miller', checkIn: '2026-03-15', checkOut: '2026-03-20', status: 'confirmed' as const },
  { id: 'e2', property: 'Villa Sunset', guest: 'คุณสมชาย (Pending)', checkIn: '2026-04-12', checkOut: '2026-04-16', status: 'pending' as const },
  { id: 'e3', property: 'Villa Hillside', guest: 'Ms. Kim (Korea)', checkIn: '2026-03-22', checkOut: '2026-03-25', status: 'confirmed' as const },
  { id: 'e4', property: 'Villa Seaview', guest: 'Songkran Group', checkIn: '2026-04-10', checkOut: '2026-04-17', status: 'pending' as const },
  { id: 'e5', property: 'Villa Beachfront', guest: 'The Johnsons', checkIn: '2026-03-12', checkOut: '2026-03-18', status: 'confirmed' as const },
];

export const communityPosts = [
  { id: 'cp1', region: 'พัทยา', author: 'คุณวิชัย', avatar: 'วช', time: '2 ชม.', message: 'แนะนำช่างแอร์ ช่างเอก 089-xxx-xxxx ซ่อมเร็ว ราคาถูก ซอยบัวขาว ดีทุกครั้งครับ 👍', likes: 12, replies: 4, category: 'vendor' },
  { id: 'cp2', region: 'ขอนแก่น', author: 'คุณแพร', avatar: 'แพ', time: '1 วัน', message: 'เทศกาลไหมปีนี้ demand สูงมาก ปีที่แล้วราคาขึ้น 40% ใครปรับราคาแล้วบ้างคะ?', likes: 8, replies: 6, category: 'pricing' },
  { id: 'cp3', region: 'ภูเก็ต', author: 'คุณมาร์ค', avatar: 'มค', time: '2 วัน', message: 'ใครมีแม่บ้านว่างบ้างครับ? ช่วง high season คนไม่พอ ต้องการ 3 คน โซนกะตะ-กะรน', likes: 5, replies: 9, category: 'staffing' },
  { id: 'cp4', region: 'พัทยา', author: 'คุณนิด', avatar: 'นด', time: '3 วัน', message: 'TM30 ออนไลน์ตอนนี้เสถียรขึ้นมากเลยค่ะ ส่งผ่าน VillaFlow ไม่เคยมีปัญหา 🎉', likes: 15, replies: 2, category: 'regulatory' },
];
